config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'

  get 'about'     => 'welcome#about'
  get 'contact'   => 'welcome#contact'
  get 'features'  => 'welcome#features'
  get 'pricing'   => 'welcome#pricing'
  get 'privacy'   => 'welcome#privacy'
  get 'tos'       => 'welcome#tos'

  resource :user, path: '/account', only: [ :show, :edit, :update ]

  post 'webhook' => 'webhook#incoming'

  resources :repositories do
    collection do
      post 'from_github_org/:github_id' => :from_github_org, as: :from_github_org
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return if user.nil?

    if user.admin?
      can :manage, :all
    end

    can :manage, User, id: user.id

    can :manage, Repository
  end
end

app/models/git_hub.rb
class GitHub
  attr_accessor :client

  # This is smelly, painted myself in a corner :(
  def initialize(user_or_token)
    if user_or_token.kind_of?(String)
      @client = Octokit::Client.new(access_token: user_or_token)
    else
      @client = user_or_token.github_client
    end
  end

  def accessible_repositories

  end

  def organizations
    client.orgs
  end

  def setup_organization(user, org_id)
    org = client.org(org_id)

    setup_repositories(user, org_id)
    install_hook_if_needed(org_id)

    org
  end

  def setup_webhook_for_development(org_id, forward_endpoint)
    install_hook_if_needed(org_id, forward_endpoint)
  end

  def webhook_url
    Rails.application.routes.url_helpers.webhook_url
  end

  protected

  def setup_repositories(user, org_id)
    Octokit.auto_paginate = true

    client.organization_repositories(org_id).each do |repo|
      saved_repo = Repository.where(github_id: repo[:id]).first_or_create do |new_repo|
        new_repo.name = repo[:name]
        new_repo.full_name = repo[:full_name]
        new_repo.private = repo[:private]
        new_repo.fork = repo[:fork]
      end

      user.user_repositories.find_or_create_by(repository_id: saved_repo.id)
    end
  end

  def find_webhooks(org_id, url)
    client.org_hooks(org_id).select { |hook| hook[:config][:url] == url }
  end

  def install_hook_if_needed(org_id, url=webhook_url)
    if find_webhooks(org_id, url).empty?
      install_org_hooks(org_id, url)
    end
  end

  def install_org_hooks(org, url)
    client.create_org_hook(
      org,
      {
        url: url,
        content_type: :json,
        secret: Rails.application.secrets.github_webhook_secret
      },
      {
        events: self.webhook_events,
        active: true
      }
    )
  end

  def webhook_events
    [ :pull_request_review_comment, :pull_request ]
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  attr_accessor :client

  scope :forked, -> { where(forked: true) }

  has_many :user_repositories, inverse_of: :repository
  has_many :users, through: :user_repositories

  validates :github_id, presence: true
  validates :name, presence: true
  validates :full_name, presence: true

  def setup(user)
    client = user.github_client
  end

  def to_param
    full_name
  end

  protected

  def check_if_webhook_installed

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [ :github ]

  has_many :user_repositories, inverse_of: :user
  has_many :repositories, through: :user_repositories

  def github_client
    raise 'User does not have a GitHub token' if github_token.nil?
    @github_client ||= Octokit::Client.new(access_token: github_token)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_for_authentication(conditions)
    where(conditions).active.first
  end

  def self.from_omniauth(auth)
    user = where(oauth_provider: auth.provider, oauth_uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password  = Devise.friendly_token[0,20]
      user.full_name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
    end

    if user.respond_to?("#{auth.provider}_token=")
      user.send("#{auth.provider}_token=", auth["credentials"]["token"])
      user.save!
    end

    user
  end
end

app/models/user_repository.rb
class UserRepository < ActiveRecord::Base
  scope :owned, -> { where(setup_here: true) }

  belongs_to :user, inverse_of: :user_repositories
  belongs_to :repository, inverse_of: :user_repositories

  validates :user, presence: true
  validates :repository, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authenticate_user!

  load_and_authorize_resource except: [ :from_github_org ], find_by: :full_name

  def index
    @repositories = current_user.repositories
  end

  def from_github_org
    github_id = params[:github_id]
    if GitHub.new(current_user).setup_organization(current_user, github_id)
      redirect_to repositories_path, notice: t(:organization_setup_complete)
    else
      redirect_to user_path, alert: t(:organization_setup_complete)
    end
  end

  def show

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: @user.oauth_provider) if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  load_and_authorize_resource

  def show
    @github = GitHub.new(current_user)
  end

  def edit

  end

  def update

  end

  private

  def user_params

  end

  def set_user
    @user = current_user
  end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  skip_before_action :verify_authenticity_token

  def incoming
    payload = validate_payload!

    Rails.logger.ap payload

    render text: "Thank you, come again."
  end

  private

  def validate_payload!
    request.body.rewind
    payload_body = request.body.read
    verify_signature(payload_body)
    JSON.parse(payload_body)
  end

  def payload_secret
    @payload_secret ||= Rails.application.secrets.github_webhook_secret
  end

  def verify_signature(payload_body)
    signature = 'sha1=' + OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha1'), payload_secret, payload_body)
    raise "Signatures didn't match!" unless Rack::Utils.secure_compare(signature, request.env['HTTP_X_HUB_SIGNATURE'])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || t('global_page_title')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans"
    = csrf_meta_tags
  body data-controller=controller_name class=controller_name
    = render "shared/menu"

    = render "shared/messages"

    - if content_for?(:content)
      == yield(:content)
    - elsif controller_name == "welcome" or controller_name == "dashboard"
      == yield
    - else
      div.container == yield

    = render "shared/footer"

app/views/repositories/index.html.slim
h1 = @repositories.model_name.human

div.list-group
- @repositories.each do |repo|
  = link_to repo.name, repository_path(repo), class: 'list-group-item'

app/views/repositories/show.html.slim
h1 = @repository.name

app/views/shared/_footer.html.slim
footer
  div.container
    div.row
      div.col-xs-4
        ul.list-inline
          li.text-muted &copy; Oil Can
          li = link_to 'About', about_path
          li = link_to 'Contact', contact_path
      div.col-xs-4.text-center
        /li = link_to '#' do
          = image_tag "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png", alt: "Facebook", size: '25x25'
        = link_to icon('twitter'), 'https://twitter.com/oilcan_io'

      div.col-xs-4.text-right
        ul.list-inline
          li = link_to 'Sign Out', destroy_user_session_path, method: :delete
          li = link_to 'Terms of Service', tos_path
          li = link_to 'Privacy Policy', privacy_path
          li = link_to icon('github', 'Fork'), 'https://github.com/oilcan/ropeburn'

app/views/shared/_menu.html.slim
nav.navbar.navbar-inverse.navbar-static-top role="navigation"
  div.container
    div.navbar-header
      button.navbar-toggle collapsed type="button" data-toggle="#navbar" aria-expanded="false" aria-controls="navbar"
        span.ar-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      - if request.path == '/'
        a.navbar-brand href='http://oilcan.io'
          'Another drop from the Oil Can
      - else
        a.navbar-brand href=root_path
          /= image_tag 'logo.svg', alt: t('navigation_name')
          = t('navigation_name')
    div.collapse.navbar-collapse id="navbar"
      ul.nav.navbar-nav.navbar-right.main-nav
        - if signed_in?
          li = link_to 'My Account', user_path
          - if current_user.admin?
            li.dropdown
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-expanded="false" Admin
              ul.dropdown-menu role="menu"
                li = link_to icon('cog', 'Organization'), '#'

        - else
          li = link_to icon('github', 'Sign Up with GitHub'), user_omniauth_authorize_path(:github)

app/views/shared/_messages.html.slim
- if notice
  div.alert.alert-success.notice.text-center = notice
- if alert
  div.alert.alert-danger.alert.text-center = alert

app/views/users/show.html.slim
h1 Your Account

p = @user.email

p Right now, we install an organization wide hook. The URL is: #{@github.webhook_url}
div.list-group
- @github.organizations.each do |org|
  = link_to org[:login], from_github_org_repositories_path(org[:login]), method: :post, class: 'list-group-item'

app/views/welcome/index.html.slim
div.container
  div.jumbotron.text-center
    h1 Ropeburn

    p &ldquo;Hey, can you look at this PR? It's been there for a few days.&rdquo; &mdash; #{link_to '@gphat', 'https://twitter.com/gphat'}